name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      env_filter:
        description: 'The filter to apply to the environment variables, i.e. "SAMPLE-DEV-*", "*-DEV", etc.'
        required: false
        default: ''
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Deploy_Infrastructure:
    runs-on: ubuntu-latest
    environment: SAMPLE-DEV-AUE

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform v1.4.4
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.4.4"

      - name: Install Ansible
        run: |
          sudo python3 -m pip install --upgrade ansible

      - name: Azure Login
        uses: azure/login@v2
        env:
          ARM_CLIENT_ID: "${{ vars.ARM_CLIENT_ID  }}"
          ARM_SUBSCRIPTION_ID: "${{ vars.ARM_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ vars.ARM_TENANT_ID }}"
        with:
          client-id: "${{ vars.ARM_CLIENT_ID  }}"
          subscription-id: "${{ vars.ARM_SUBSCRIPTION_ID }}"
          tenant-id: "${{ vars.ARM_TENANT_ID }}"

      - name: Create or Update Resource Group and Core Network
        working-directory: infra/
        env:
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
        run: |
          az version
          az account show
          
          export ARM_SUBSCRIPTION_ID=$(az account list --query "[?isDefault].id | [0]" -o tsv)
          export ANSIBLE_DEPRECATION_WARNINGS=False
          
          # Use GITHUB_HEAD_REF for pull requests and GITHUB_REF_NAME for branch pushes 
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
          
          ansible-playbook -v playbook.yml --extra-vars app_env=dev --tags preview
          
          if [ "$BRANCH_NAME" == "dev" ]; then
              ansible-playbook -v playbook.yml --extra-vars app_env=dev --tags deploy
          fi
